server:
  port: 8082

spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27018,mongo3:27017/catalog_db?replicaSet=rs0

# Logging
logging:
  level:
    com.flashsale: info
    org.springframework: warn