server:
  port: 8083

spring:
  application:
    name: reservation-service
  data:
    mongodb:
      uri: mongodb://mongo1:27017,mongo2:27018,mongo3:27017/reservation_db?replicaSet=rs0
      auto-index-creation: true
  kafka:
    producer:
      acks: all
      properties:
        enable.idempotence: true

app:
  jwt:
    secret: ${JWT_SECRET:flash-sale-engine-secret-key-change-in-production}

# Logging
logging:
  level:
    com.flashsale: info
    org.springframework: warn
